name: Generate Images

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Program
        run: yarn add @vladaviedov/gh-lang-stats
      - name: Run Program
        run: npx gh-lang-stats
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      - name: Commit
        run: |
          git config user.name "Test"
          git config user.email "test@example.com"
          git add .
          git commit -m "generated images" --allow-empty
          git push origin master
